export { default as Activities } from "./Activities"
export { default as ActivityCreate } from './ActivityCreate'
export { default as Home } from './Home'
export { default as AddActivityToRoutine } from './AddActivityToRoutineForm'
export { default as Login } from './Login'
export { default as MyRoutines} from './MyRoutines'
export { default as NavBar } from './NavBar'
export { default as Register } from './Register'
export { default as RoutineActivityEdit } from './RoutineActivityEdit'
export { default as RoutineEdit } from './RoutineEdit'
export { default as Routines } from './Routines'
export { default as RoutinesCreate } from './RoutinesCreate'
export { default as Footer } from './Footer'